#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservas_Vuelo.DataLayer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Reservas_Vuelo")]
	public partial class DataLayerDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAsiento_Avion(Asiento_Avion instance);
    partial void UpdateAsiento_Avion(Asiento_Avion instance);
    partial void DeleteAsiento_Avion(Asiento_Avion instance);
    partial void InsertAsiento_Viaje(Asiento_Viaje instance);
    partial void UpdateAsiento_Viaje(Asiento_Viaje instance);
    partial void DeleteAsiento_Viaje(Asiento_Viaje instance);
    partial void InsertAvion(Avion instance);
    partial void UpdateAvion(Avion instance);
    partial void DeleteAvion(Avion instance);
    partial void InsertVenta(Venta instance);
    partial void UpdateVenta(Venta instance);
    partial void DeleteVenta(Venta instance);
    partial void InsertViaje(Viaje instance);
    partial void UpdateViaje(Viaje instance);
    partial void DeleteViaje(Viaje instance);
    partial void InsertVuelo(Vuelo instance);
    partial void UpdateVuelo(Vuelo instance);
    partial void DeleteVuelo(Vuelo instance);
    #endregion
		
		public DataLayerDataContext() : 
				base(global::Reservas_Vuelo.DataLayer.Properties.Settings.Default.Reservas_VueloConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataLayerDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataLayerDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataLayerDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataLayerDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Asiento_Avion> Asiento_Avions
		{
			get
			{
				return this.GetTable<Asiento_Avion>();
			}
		}
		
		public System.Data.Linq.Table<Asiento_Viaje> Asiento_Viajes
		{
			get
			{
				return this.GetTable<Asiento_Viaje>();
			}
		}
		
		public System.Data.Linq.Table<Asientos_Venta> Asientos_Ventas
		{
			get
			{
				return this.GetTable<Asientos_Venta>();
			}
		}
		
		public System.Data.Linq.Table<Avion> Avions
		{
			get
			{
				return this.GetTable<Avion>();
			}
		}
		
		public System.Data.Linq.Table<Ciudad> Ciudads
		{
			get
			{
				return this.GetTable<Ciudad>();
			}
		}
		
		public System.Data.Linq.Table<Venta> Ventas
		{
			get
			{
				return this.GetTable<Venta>();
			}
		}
		
		public System.Data.Linq.Table<Viaje> Viajes
		{
			get
			{
				return this.GetTable<Viaje>();
			}
		}
		
		public System.Data.Linq.Table<Vuelo> Vuelos
		{
			get
			{
				return this.GetTable<Vuelo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Asiento_Avion")]
	public partial class Asiento_Avion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _Id_Avion;
		
		private string _Descripcion;
		
		private EntitySet<Asiento_Viaje> _Asiento_Viajes;
		
		private EntityRef<Avion> _Avion;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnId_AvionChanging(int value);
    partial void OnId_AvionChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    #endregion
		
		public Asiento_Avion()
		{
			this._Asiento_Viajes = new EntitySet<Asiento_Viaje>(new Action<Asiento_Viaje>(this.attach_Asiento_Viajes), new Action<Asiento_Viaje>(this.detach_Asiento_Viajes));
			this._Avion = default(EntityRef<Avion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Avion", DbType="Int NOT NULL")]
		public int Id_Avion
		{
			get
			{
				return this._Id_Avion;
			}
			set
			{
				if ((this._Id_Avion != value))
				{
					if (this._Avion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_AvionChanging(value);
					this.SendPropertyChanging();
					this._Id_Avion = value;
					this.SendPropertyChanged("Id_Avion");
					this.OnId_AvionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Asiento_Avion_Asiento_Viaje", Storage="_Asiento_Viajes", ThisKey="Id", OtherKey="Id_Asiento_Avion")]
		public EntitySet<Asiento_Viaje> Asiento_Viajes
		{
			get
			{
				return this._Asiento_Viajes;
			}
			set
			{
				this._Asiento_Viajes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Avion_Asiento_Avion", Storage="_Avion", ThisKey="Id_Avion", OtherKey="Id", IsForeignKey=true)]
		public Avion Avion
		{
			get
			{
				return this._Avion.Entity;
			}
			set
			{
				Avion previousValue = this._Avion.Entity;
				if (((previousValue != value) 
							|| (this._Avion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Avion.Entity = null;
						previousValue.Asiento_Avions.Remove(this);
					}
					this._Avion.Entity = value;
					if ((value != null))
					{
						value.Asiento_Avions.Add(this);
						this._Id_Avion = value.Id;
					}
					else
					{
						this._Id_Avion = default(int);
					}
					this.SendPropertyChanged("Avion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Asiento_Viajes(Asiento_Viaje entity)
		{
			this.SendPropertyChanging();
			entity.Asiento_Avion = this;
		}
		
		private void detach_Asiento_Viajes(Asiento_Viaje entity)
		{
			this.SendPropertyChanging();
			entity.Asiento_Avion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Asiento_Viaje")]
	public partial class Asiento_Viaje : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _Id_Viaje;
		
		private int _Id_Asiento_Avion;
		
		private int _Id_Vuelo;
		
		private int _Id_Avion;
		
		private EntityRef<Asiento_Avion> _Asiento_Avion;
		
		private EntityRef<Avion> _Avion;
		
		private EntityRef<Viaje> _Viaje;
		
		private EntityRef<Vuelo> _Vuelo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnId_ViajeChanging(int value);
    partial void OnId_ViajeChanged();
    partial void OnId_Asiento_AvionChanging(int value);
    partial void OnId_Asiento_AvionChanged();
    partial void OnId_VueloChanging(int value);
    partial void OnId_VueloChanged();
    partial void OnId_AvionChanging(int value);
    partial void OnId_AvionChanged();
    #endregion
		
		public Asiento_Viaje()
		{
			this._Asiento_Avion = default(EntityRef<Asiento_Avion>);
			this._Avion = default(EntityRef<Avion>);
			this._Viaje = default(EntityRef<Viaje>);
			this._Vuelo = default(EntityRef<Vuelo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Viaje", DbType="Int NOT NULL")]
		public int Id_Viaje
		{
			get
			{
				return this._Id_Viaje;
			}
			set
			{
				if ((this._Id_Viaje != value))
				{
					if (this._Viaje.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_ViajeChanging(value);
					this.SendPropertyChanging();
					this._Id_Viaje = value;
					this.SendPropertyChanged("Id_Viaje");
					this.OnId_ViajeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Asiento_Avion", DbType="Int NOT NULL")]
		public int Id_Asiento_Avion
		{
			get
			{
				return this._Id_Asiento_Avion;
			}
			set
			{
				if ((this._Id_Asiento_Avion != value))
				{
					if (this._Asiento_Avion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_Asiento_AvionChanging(value);
					this.SendPropertyChanging();
					this._Id_Asiento_Avion = value;
					this.SendPropertyChanged("Id_Asiento_Avion");
					this.OnId_Asiento_AvionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Vuelo", DbType="Int NOT NULL")]
		public int Id_Vuelo
		{
			get
			{
				return this._Id_Vuelo;
			}
			set
			{
				if ((this._Id_Vuelo != value))
				{
					if (this._Vuelo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_VueloChanging(value);
					this.SendPropertyChanging();
					this._Id_Vuelo = value;
					this.SendPropertyChanged("Id_Vuelo");
					this.OnId_VueloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Avion", DbType="Int NOT NULL")]
		public int Id_Avion
		{
			get
			{
				return this._Id_Avion;
			}
			set
			{
				if ((this._Id_Avion != value))
				{
					if (this._Avion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_AvionChanging(value);
					this.SendPropertyChanging();
					this._Id_Avion = value;
					this.SendPropertyChanged("Id_Avion");
					this.OnId_AvionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Asiento_Avion_Asiento_Viaje", Storage="_Asiento_Avion", ThisKey="Id_Asiento_Avion", OtherKey="Id", IsForeignKey=true)]
		public Asiento_Avion Asiento_Avion
		{
			get
			{
				return this._Asiento_Avion.Entity;
			}
			set
			{
				Asiento_Avion previousValue = this._Asiento_Avion.Entity;
				if (((previousValue != value) 
							|| (this._Asiento_Avion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Asiento_Avion.Entity = null;
						previousValue.Asiento_Viajes.Remove(this);
					}
					this._Asiento_Avion.Entity = value;
					if ((value != null))
					{
						value.Asiento_Viajes.Add(this);
						this._Id_Asiento_Avion = value.Id;
					}
					else
					{
						this._Id_Asiento_Avion = default(int);
					}
					this.SendPropertyChanged("Asiento_Avion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Avion_Asiento_Viaje", Storage="_Avion", ThisKey="Id_Avion", OtherKey="Id", IsForeignKey=true)]
		public Avion Avion
		{
			get
			{
				return this._Avion.Entity;
			}
			set
			{
				Avion previousValue = this._Avion.Entity;
				if (((previousValue != value) 
							|| (this._Avion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Avion.Entity = null;
						previousValue.Asiento_Viajes.Remove(this);
					}
					this._Avion.Entity = value;
					if ((value != null))
					{
						value.Asiento_Viajes.Add(this);
						this._Id_Avion = value.Id;
					}
					else
					{
						this._Id_Avion = default(int);
					}
					this.SendPropertyChanged("Avion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Viaje_Asiento_Viaje", Storage="_Viaje", ThisKey="Id_Viaje", OtherKey="Id", IsForeignKey=true)]
		public Viaje Viaje
		{
			get
			{
				return this._Viaje.Entity;
			}
			set
			{
				Viaje previousValue = this._Viaje.Entity;
				if (((previousValue != value) 
							|| (this._Viaje.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Viaje.Entity = null;
						previousValue.Asiento_Viajes.Remove(this);
					}
					this._Viaje.Entity = value;
					if ((value != null))
					{
						value.Asiento_Viajes.Add(this);
						this._Id_Viaje = value.Id;
					}
					else
					{
						this._Id_Viaje = default(int);
					}
					this.SendPropertyChanged("Viaje");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Vuelo_Asiento_Viaje", Storage="_Vuelo", ThisKey="Id_Vuelo", OtherKey="Id", IsForeignKey=true)]
		public Vuelo Vuelo
		{
			get
			{
				return this._Vuelo.Entity;
			}
			set
			{
				Vuelo previousValue = this._Vuelo.Entity;
				if (((previousValue != value) 
							|| (this._Vuelo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Vuelo.Entity = null;
						previousValue.Asiento_Viajes.Remove(this);
					}
					this._Vuelo.Entity = value;
					if ((value != null))
					{
						value.Asiento_Viajes.Add(this);
						this._Id_Vuelo = value.Id;
					}
					else
					{
						this._Id_Vuelo = default(int);
					}
					this.SendPropertyChanged("Vuelo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Asientos_Venta")]
	public partial class Asientos_Venta
	{
		
		private int _Id_Ventas;
		
		private int _Id_Asientos_Viaje;
		
		public Asientos_Venta()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Ventas", DbType="Int NOT NULL")]
		public int Id_Ventas
		{
			get
			{
				return this._Id_Ventas;
			}
			set
			{
				if ((this._Id_Ventas != value))
				{
					this._Id_Ventas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Asientos_Viaje", DbType="Int NOT NULL")]
		public int Id_Asientos_Viaje
		{
			get
			{
				return this._Id_Asientos_Viaje;
			}
			set
			{
				if ((this._Id_Asientos_Viaje != value))
				{
					this._Id_Asientos_Viaje = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Avion")]
	public partial class Avion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Descripcion;
		
		private EntitySet<Asiento_Avion> _Asiento_Avions;
		
		private EntitySet<Asiento_Viaje> _Asiento_Viajes;
		
		private EntitySet<Vuelo> _Vuelos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    #endregion
		
		public Avion()
		{
			this._Asiento_Avions = new EntitySet<Asiento_Avion>(new Action<Asiento_Avion>(this.attach_Asiento_Avions), new Action<Asiento_Avion>(this.detach_Asiento_Avions));
			this._Asiento_Viajes = new EntitySet<Asiento_Viaje>(new Action<Asiento_Viaje>(this.attach_Asiento_Viajes), new Action<Asiento_Viaje>(this.detach_Asiento_Viajes));
			this._Vuelos = new EntitySet<Vuelo>(new Action<Vuelo>(this.attach_Vuelos), new Action<Vuelo>(this.detach_Vuelos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(25)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Avion_Asiento_Avion", Storage="_Asiento_Avions", ThisKey="Id", OtherKey="Id_Avion")]
		public EntitySet<Asiento_Avion> Asiento_Avions
		{
			get
			{
				return this._Asiento_Avions;
			}
			set
			{
				this._Asiento_Avions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Avion_Asiento_Viaje", Storage="_Asiento_Viajes", ThisKey="Id", OtherKey="Id_Avion")]
		public EntitySet<Asiento_Viaje> Asiento_Viajes
		{
			get
			{
				return this._Asiento_Viajes;
			}
			set
			{
				this._Asiento_Viajes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Avion_Vuelo", Storage="_Vuelos", ThisKey="Id", OtherKey="Id_Avion")]
		public EntitySet<Vuelo> Vuelos
		{
			get
			{
				return this._Vuelos;
			}
			set
			{
				this._Vuelos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Asiento_Avions(Asiento_Avion entity)
		{
			this.SendPropertyChanging();
			entity.Avion = this;
		}
		
		private void detach_Asiento_Avions(Asiento_Avion entity)
		{
			this.SendPropertyChanging();
			entity.Avion = null;
		}
		
		private void attach_Asiento_Viajes(Asiento_Viaje entity)
		{
			this.SendPropertyChanging();
			entity.Avion = this;
		}
		
		private void detach_Asiento_Viajes(Asiento_Viaje entity)
		{
			this.SendPropertyChanging();
			entity.Avion = null;
		}
		
		private void attach_Vuelos(Vuelo entity)
		{
			this.SendPropertyChanging();
			entity.Avion = this;
		}
		
		private void detach_Vuelos(Vuelo entity)
		{
			this.SendPropertyChanging();
			entity.Avion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ciudad")]
	public partial class Ciudad
	{
		
		private string _Nombre;
		
		private string _Codigo;
		
		public Ciudad()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Venta")]
	public partial class Venta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _Tarjeta;
		
		private string _Ccv;
		
		private int _Exp;
		
		private string _Dir_Cobro;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnTarjetaChanging(string value);
    partial void OnTarjetaChanged();
    partial void OnCcvChanging(string value);
    partial void OnCcvChanged();
    partial void OnExpChanging(int value);
    partial void OnExpChanged();
    partial void OnDir_CobroChanging(string value);
    partial void OnDir_CobroChanged();
    #endregion
		
		public Venta()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarjeta", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string Tarjeta
		{
			get
			{
				return this._Tarjeta;
			}
			set
			{
				if ((this._Tarjeta != value))
				{
					this.OnTarjetaChanging(value);
					this.SendPropertyChanging();
					this._Tarjeta = value;
					this.SendPropertyChanged("Tarjeta");
					this.OnTarjetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ccv", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Ccv
		{
			get
			{
				return this._Ccv;
			}
			set
			{
				if ((this._Ccv != value))
				{
					this.OnCcvChanging(value);
					this.SendPropertyChanging();
					this._Ccv = value;
					this.SendPropertyChanged("Ccv");
					this.OnCcvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Exp", DbType="Int NOT NULL")]
		public int Exp
		{
			get
			{
				return this._Exp;
			}
			set
			{
				if ((this._Exp != value))
				{
					this.OnExpChanging(value);
					this.SendPropertyChanging();
					this._Exp = value;
					this.SendPropertyChanged("Exp");
					this.OnExpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dir_Cobro", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Dir_Cobro
		{
			get
			{
				return this._Dir_Cobro;
			}
			set
			{
				if ((this._Dir_Cobro != value))
				{
					this.OnDir_CobroChanging(value);
					this.SendPropertyChanging();
					this._Dir_Cobro = value;
					this.SendPropertyChanged("Dir_Cobro");
					this.OnDir_CobroChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Viaje")]
	public partial class Viaje : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _Id_Vuelo;
		
		private System.DateTime _Fecha;
		
		private EntitySet<Asiento_Viaje> _Asiento_Viajes;
		
		private EntityRef<Vuelo> _Vuelo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnId_VueloChanging(int value);
    partial void OnId_VueloChanged();
    partial void OnFechaChanging(System.DateTime value);
    partial void OnFechaChanged();
    #endregion
		
		public Viaje()
		{
			this._Asiento_Viajes = new EntitySet<Asiento_Viaje>(new Action<Asiento_Viaje>(this.attach_Asiento_Viajes), new Action<Asiento_Viaje>(this.detach_Asiento_Viajes));
			this._Vuelo = default(EntityRef<Vuelo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Vuelo", DbType="Int NOT NULL")]
		public int Id_Vuelo
		{
			get
			{
				return this._Id_Vuelo;
			}
			set
			{
				if ((this._Id_Vuelo != value))
				{
					if (this._Vuelo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_VueloChanging(value);
					this.SendPropertyChanging();
					this._Id_Vuelo = value;
					this.SendPropertyChanged("Id_Vuelo");
					this.OnId_VueloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Viaje_Asiento_Viaje", Storage="_Asiento_Viajes", ThisKey="Id", OtherKey="Id_Viaje")]
		public EntitySet<Asiento_Viaje> Asiento_Viajes
		{
			get
			{
				return this._Asiento_Viajes;
			}
			set
			{
				this._Asiento_Viajes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Vuelo_Viaje", Storage="_Vuelo", ThisKey="Id_Vuelo", OtherKey="Id", IsForeignKey=true)]
		public Vuelo Vuelo
		{
			get
			{
				return this._Vuelo.Entity;
			}
			set
			{
				Vuelo previousValue = this._Vuelo.Entity;
				if (((previousValue != value) 
							|| (this._Vuelo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Vuelo.Entity = null;
						previousValue.Viajes.Remove(this);
					}
					this._Vuelo.Entity = value;
					if ((value != null))
					{
						value.Viajes.Add(this);
						this._Id_Vuelo = value.Id;
					}
					else
					{
						this._Id_Vuelo = default(int);
					}
					this.SendPropertyChanged("Vuelo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Asiento_Viajes(Asiento_Viaje entity)
		{
			this.SendPropertyChanging();
			entity.Viaje = this;
		}
		
		private void detach_Asiento_Viajes(Asiento_Viaje entity)
		{
			this.SendPropertyChanging();
			entity.Viaje = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vuelo")]
	public partial class Vuelo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Origen;
		
		private string _Destino;
		
		private string _Hora_Salida;
		
		private string _Hora_Llegada;
		
		private int _Id_Avion;
		
		private EntitySet<Asiento_Viaje> _Asiento_Viajes;
		
		private EntitySet<Viaje> _Viajes;
		
		private EntityRef<Avion> _Avion;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnOrigenChanging(string value);
    partial void OnOrigenChanged();
    partial void OnDestinoChanging(string value);
    partial void OnDestinoChanged();
    partial void OnHora_SalidaChanging(string value);
    partial void OnHora_SalidaChanged();
    partial void OnHora_LlegadaChanging(string value);
    partial void OnHora_LlegadaChanged();
    partial void OnId_AvionChanging(int value);
    partial void OnId_AvionChanged();
    #endregion
		
		public Vuelo()
		{
			this._Asiento_Viajes = new EntitySet<Asiento_Viaje>(new Action<Asiento_Viaje>(this.attach_Asiento_Viajes), new Action<Asiento_Viaje>(this.detach_Asiento_Viajes));
			this._Viajes = new EntitySet<Viaje>(new Action<Viaje>(this.attach_Viajes), new Action<Viaje>(this.detach_Viajes));
			this._Avion = default(EntityRef<Avion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Origen", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Origen
		{
			get
			{
				return this._Origen;
			}
			set
			{
				if ((this._Origen != value))
				{
					this.OnOrigenChanging(value);
					this.SendPropertyChanging();
					this._Origen = value;
					this.SendPropertyChanged("Origen");
					this.OnOrigenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Destino", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Destino
		{
			get
			{
				return this._Destino;
			}
			set
			{
				if ((this._Destino != value))
				{
					this.OnDestinoChanging(value);
					this.SendPropertyChanging();
					this._Destino = value;
					this.SendPropertyChanged("Destino");
					this.OnDestinoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hora_Salida", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Hora_Salida
		{
			get
			{
				return this._Hora_Salida;
			}
			set
			{
				if ((this._Hora_Salida != value))
				{
					this.OnHora_SalidaChanging(value);
					this.SendPropertyChanging();
					this._Hora_Salida = value;
					this.SendPropertyChanged("Hora_Salida");
					this.OnHora_SalidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hora_Llegada", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Hora_Llegada
		{
			get
			{
				return this._Hora_Llegada;
			}
			set
			{
				if ((this._Hora_Llegada != value))
				{
					this.OnHora_LlegadaChanging(value);
					this.SendPropertyChanging();
					this._Hora_Llegada = value;
					this.SendPropertyChanged("Hora_Llegada");
					this.OnHora_LlegadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Avion", DbType="Int NOT NULL")]
		public int Id_Avion
		{
			get
			{
				return this._Id_Avion;
			}
			set
			{
				if ((this._Id_Avion != value))
				{
					if (this._Avion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_AvionChanging(value);
					this.SendPropertyChanging();
					this._Id_Avion = value;
					this.SendPropertyChanged("Id_Avion");
					this.OnId_AvionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Vuelo_Asiento_Viaje", Storage="_Asiento_Viajes", ThisKey="Id", OtherKey="Id_Vuelo")]
		public EntitySet<Asiento_Viaje> Asiento_Viajes
		{
			get
			{
				return this._Asiento_Viajes;
			}
			set
			{
				this._Asiento_Viajes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Vuelo_Viaje", Storage="_Viajes", ThisKey="Id", OtherKey="Id_Vuelo")]
		public EntitySet<Viaje> Viajes
		{
			get
			{
				return this._Viajes;
			}
			set
			{
				this._Viajes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Avion_Vuelo", Storage="_Avion", ThisKey="Id_Avion", OtherKey="Id", IsForeignKey=true)]
		public Avion Avion
		{
			get
			{
				return this._Avion.Entity;
			}
			set
			{
				Avion previousValue = this._Avion.Entity;
				if (((previousValue != value) 
							|| (this._Avion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Avion.Entity = null;
						previousValue.Vuelos.Remove(this);
					}
					this._Avion.Entity = value;
					if ((value != null))
					{
						value.Vuelos.Add(this);
						this._Id_Avion = value.Id;
					}
					else
					{
						this._Id_Avion = default(int);
					}
					this.SendPropertyChanged("Avion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Asiento_Viajes(Asiento_Viaje entity)
		{
			this.SendPropertyChanging();
			entity.Vuelo = this;
		}
		
		private void detach_Asiento_Viajes(Asiento_Viaje entity)
		{
			this.SendPropertyChanging();
			entity.Vuelo = null;
		}
		
		private void attach_Viajes(Viaje entity)
		{
			this.SendPropertyChanging();
			entity.Vuelo = this;
		}
		
		private void detach_Viajes(Viaje entity)
		{
			this.SendPropertyChanging();
			entity.Vuelo = null;
		}
	}
}
#pragma warning restore 1591
